name: Run Trading Bot

on:
  schedule:
    - cron: "30 3 * * *"   # runs every day at 03:30 UTC (adjust for your timezone)
  workflow_dispatch:        # allows manual run from Actions tab

jobs:
  run-bot:
    runs-on: ubuntu-latest
    secrets: inherit

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run script
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        GOOGLE_CREDS_JSON: ${{ secrets.CREDS }}
      run: python main.py
